[Variables]

;When editing settings don't forget to
; save the file
; right click skin -> refresh skin

Color1=7C86CE
;Default: 7C86CE
;Left Background Color


Color2=5A69C6
;Default: 5A69C6
;Right Background Color


;Some colors:
; 7C86CE, 5A69C6 - Blue
; 4A968C, 2A8274 - Green
; F86194, C61063 - Red


TextColor=ffffff
;Default: ffffff

TextShadowColor=00000040
;Default: 00000040


IconColor=ffffff
;Default: ffffff

IconShadowColor=00000040
;Default: 00000040

SettingsHoverColor=ffffff88
;Default: ffffff88

Font=Roboto Light
;Default: Roboto Light


ShowSettings=1
;Default: 1
;1 to show, 0 to hide. You can still right click to find the settings
