set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'myusuf3/numbers.vim'

" Color Themes
Plugin 'notpratheek/vim-luna'
if has ('gui_running')
   syntax on
   colorscheme luna
endif

""""""""
if has('gui_running')
  set guifont=Inconsolata_for_Powerline:h13
  set guioptions -=T
  set guioptions -=m
  set guioptions -=r
endif
set number
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set nospell
set visualbell

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

set ruler

set undolevels=1000
set backspace=indent,eol,start

"Vim-Airlines
set encoding=utf-8
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'luna'
set laststatus=2
  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif
let g:airline_powerline_fonts = 1

"Rainbow Parenthesis

