[Variables]

;When editing settings don't forget to
; save the file
; right click skin -> refresh skin

CityId=5128581
;Find your city id by going to "http://openweathermap.org/", finding your city and pasting the
;last section here (http://openweathermap.org/city/5128581) -> 5128581


Units=metric
;Default: metric
;Valid values are "metric" - °C, "imperial" - °F and nothing (Units="") - K


Prefix1="High: "
Prefix2="Low: "
Prefix3="Current Temp: "
;Default: "High: ", "Low: ", "Current Temp: "
