#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m 0 -width 1500)

another=$(echo "RELOAD
LOGOUT
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "System: ")


if [ "$another" == "RELOAD" ] ; then
	xrdb -load ~/.Xdefaults; 
	i3-msg reload; 
	i3-msg restart;
elif [ "$another" == "LOGOUT" ] ; then
	prompt "i3-msg exit" LOGOUT
	
elif [ "$another" == "REBOOT" ] ; then
	prompt "reboot" REBOOT
	
elif [ "$another" == "POWEROFF" ] ; then
	prompt "poweroff" POWEROFF	

else
    echo $another
fi


