[Variables]

Bands=72
; Number of bars - Activate Fountain of Colors\GenerateBands skin after changing this value

BarGap=7
BarWidth=10
BarHeight=250

AverageSize=4
; "Smoothness" - Number of past measure values used to increase continuity

FFTSize=6144
FFTOverlap=(#FFTSize#*0.5)
FFTAttack=0
FFTDecay=275
FreqMin=20
FreqMax=20000
Sensitivity=32
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

Colors=Custom

PaletteColor1=255,70,0
; 129,138,113
PaletteColor2=255,70,0
; 5,5,5
PaletteColor3=255,70,0
; 118,102,128
PaletteColor4=255,70,0
;0,0,0

TransitionTime=8
hBlendingMultiplier=0.4
vBlendingMultiplier=1.2
OpacityLower=153
OpacityUpper=255
OpacityMultiplier=1

ModeKeyboard=0
FirstBandIndex=1

; Environment variables for settings window
SkinGroup=FountainOfColors
Config=Fountain of Colors\Clone_2
ConfigPath=C:\Users\ayman_000\Documents\Rainmeter\Skins\Fountain of Colors\Clone_2\Clone_2.ini
WriteVariable=PaletteColor3
Angle=0
Invert=0
Channel=Avg
Port=Output
ID=
